Building minor-packages inside Vagrant machine.

diff --git a/rpms/scripts/psrpm_build_perl b/rpms/scripts/psrpm_build_perl
--- a/rpms/scripts/psrpm_build_perl
+++ b/rpms/scripts/psrpm_build_perl
@@ -50,14 +50,22 @@ else
 fi
 
 # Build tarball
-make dist
-if [ "$?" -ne "0" ]; then
-    echo "Error running make dist"
-    exit 1
+if [ "$GITREPO" == "minor-packages" ]; then
+    cd $PACKAGE
+    # .patch files might not exist for all projects
+    for f in `ls *.patch bootstrap.sh 2> /dev/null` ; do
+            cp $f /home/vagrant/rpmbuild/SOURCES/
+    done
+else
+    make dist
+    if [ "$?" -ne "0" ]; then
+        echo "Error running make dist"
+        exit 1
+    fi
 fi
 
 #Copy tarball to rpm build environment
-cp ${PACKAGE}-*.tar.gz /home/vagrant/rpmbuild/SOURCES/
+cp ${PACKAGE}-*.tar.* /home/vagrant/rpmbuild/SOURCES/
 if [ "$?" -ne "0" ]; then
     echo "Error copying source"
     exit 1
